language: go
sudo: required
services:
- docker
env:
  - IMAGE_NAME=limed/travis-test
  - COMMIT_HASH=${TRAVIS_COMMIT::8}
  - secure: ySV5JqntUsW6rJAkj67bazotOACR2MnrtulfDlUe/XQvPagim01xnKSbxCNCj90Yfai265sSh0wt/RenhEDmNAN7pabdNb0/wBm3qDQ35FgfPXfrbnr1OOWs8CmY0eHWgfuNM/NkGcsDeYma3epB+P+sdpQA/lPu6ahr93VVxWRzoOYjp3ThiJe+CtkpwNkFllLj6VeQUff7JGCvF88rmNZzPHYqAe7UjKQu/L5Pj0FdkPbhysm4r7l5Bspiyjtk6QoNdFa+9GwmcfCzheAfg0Z6F+ypLDU9Ia2Wla1K/nA+6W+DpcSpC2XElvR81YgMRCwErz0QWMvk+nN3Pv8h0uiTU/sVeARR+Zt3JAFBPT9dY9lIMBG+0GPegMOg46Eb90HPA4my0dJ9m0nDizOnR2bed9tyQZFQdW3oYxEfkyY5xoQ/boPSg3HUQd4Wi3yInTT+eMa8kHkNQl7H7eb9mKT1Ow9KY/gUvx+441Iq3kg5/x0H6OTI9Lm6BoXfLJBVwLZkrKyfVWhaGdv1PIOnwHpqfx/U8nUDzGO+BEdHRZ3QzkDHUKn24VovJOF8yRUJTdP+HVFCOr3TSZlkrfwteFNF6jnZxB45hI0vUEaBd2QtC6Hk7xs3xaSwPFjgOZ4fC1r/3CNQh9iK190Is8ddMuEUVWoQpr2+z8m++Cl4AjA=
  - secure: bkyMTHhMuL4XDuy7NQpFtDe7IAsPErDukDZ7yy3S7noSzvhqXEIiLuObEoxxX3JP8PS7IQ4aWabExlctaAr53DhiX5if9qtr8R3YPVa3hJ2FGmVrVusZ3kG45PHrA46A9N2gKhnV71m0mjd2y1Y647FYyOa0oYBa1gLwSBnPsuuQacacpIob7JBwIev18EBt9+L6Gt+9p9iO6yIf6SuLzolT88+ArCT/5NqpJrR6uRqk+6XzHUV2VAVYxXmY2Cu8870wG/V6sXORjcAKg7Ltv5NyHQuslT29cGJxeNgGMAvX3mWkNmKmMRsnVoauJyf8+rTgP68ZSbQ/so3jNatZTadUA9vJQnE9QG6o4s45iVxnSJBbuafYO7wNc5+zTAaQVNntrdtK7H2FZVU2R6BPl0xZh5e2oWKt0LEO0an0Ld/5d45A0FC44cJk3Vm++K4NJ8w2/h0miGRdTq7hOuSIG/8/PHU/hCdI/IcQwoJdMXQjFhwQnT7fUF5XVzZlXUkMkNMBBRbLMNLVylASD7pzkAbE2VgzDhfR3XtcLXMk/tTCyd3lMl8Dl1VhRUz3NKCEUoFF6v9CC2Te/MrDjXTTkKwPDUe63ChWGtCAaGF+BY3k96pVeGT+s56aXHGybtSSvauT2TTe0m55M1WuCD3qs6HJsZjirX+Wo8f/lcGftO4=

before_install:
- docker logout
- echo $IMAGE_NAME
- echo $COMMIT_HASH

stages:
  - name: Build Docker Image
    if: branch = master

jobs:
  include:
  - stage: Build Docker Image
    script:
    - echo "Logging in to dockerhub"
    - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
    - echo "Building image"
    - docker build -t $IMAGE_NAME:latest .
    - docker images
    if: "(branch = master)"
