language: go

sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=limed/travis-test
    - COMMIT_HASH=${TRAVIS_COMMIT::8}
    - secure: "tH1TVhvAC8qy+DC7jnSJCxRsvYu4knPHmpjbNA0YKK2V7j+T3m2dl4ezYolhBLTlf+SdEfBQQhneWaSq0/F/kdQOrYbGolniXNjvnVJFd3os1TJ3fBDRihicPraKSJmXaaohdoBXPokOmkwaUj4Z0Ahmboy8RHAwdZGNVy/M84uiaUuri72FkpxI26AbRnjCnbPxHags4EiYhs0hZ+pPEPrjP7rLzzoSdxl/IzsRiNhrmnrQQFBiJ28Lz4NbXS3sBRP0zw7vyqSAnzTH7Ifx1dHI33+LVa97xJSpyT0ixlJ2wwgv1sPeJPUggtN8mYkYRhgg6UMA7VU5lKkQmZkgAjCGNfF575H8LJzaD9dI9kZ/iISOf4JQ42T8cHFSuTCwjkV4LlQ/63yYmaqABKtLzlSi+3fVs8hb9Kic2uf+AqLALmrARquVTTP3sRk2vh46+dbQHkstEGwNahafNENpnw3Vc8RonhxWWMCaQ5/r8kKKBrw5xF4meHtU/T39o+iwsFe5CBQXIR00+5r0eIkDifKvl9j2hguvKV0kjwUNWRqTISrv8obTgMbdSodb/9C8/1YuCWz28DePPJ+cT98+4RRUvokUqP1Gds0cU+EV52qt3FmylgxaZhZPoDZx32mc9PJdd04yVUJEcU7db+nyCJsxNsuGj3TIinxSLs74ZtM="
    - secure: "L5IsJAPgN7u8hJJF+ZNxZypjFDxqEFmEfep1WyMOHYJqqyWPC+MXgzRMKdvh8vWx4M4fIgkBJBjePDsigHFxb0JvbQxT11xEHYYZb9TPUN+Ekq8sqt4uje4Vl6zvGVIokqfafiePvwxm8bTlUy55zAkQzd6SpVhsnG3dCQ/Fa+rESWYa7JoO6ODUdpReKi2SlCF9FN0FYk6NZ2FFoEJG2y01t3rxiZA1nuHUhPbkS2AEH6jqY6gjl31Ock/ON3Wch8g35aZmOGKA+gkm9cZ71ZIt9pazE4s4EoeI/bA2QVqDZ5qz2xW7y+Yx8X32Ok6xLjJAHnJRdSkgCJb2tX6Fd6HL6FcArOA8v0YeEe84QIDtHHLe6v1ePZ6gJayZeNbShzKH4yqwzCfmzsCtNeYoL1PevNEpdCqNoUO/VumLv5R7IBS8RJqcOUVF3+xI0yykNHszzOLxWBvpzgWxB2coKTFNzlCEeo4xaBGP4j0oYQUfLt6SnSxhHqxO+EcSzY4GNSMM5oWhnoYhg1rxmg8EPJ5CPXI4aB4w5Q/9vFfS1nAgCLxzPZMboajICqL/BGimUCYpQdUvgb0PonH8AYxrGHEnE5Hv/FrkuMVUqDIgU53ZU+zzDpJWlcy1OBZ4fXKU9Xt1eCxhSpldE8OPakBuxqQiiUcLSRutvNmvxJS5cuY="

before_install:
  - echo "Logging in to dockerhub"
  - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USER}" --password-stdin

jobs:
  include:
    - stage: Build Docker Image
      script:
        - echo "Building image"
        - docker build -t ${IMAGE_NAME}:latest -t ${IMAGE_NAME}:${COMMIT_HASH} .
        - docker images
      if: (branch = master)
