language: bash
sudo: required
services:
- docker
env:
  matrix:
  - IMAGE_NAME=limed/travis-test
  - COMMIT_HASH=${TRAVIS_COMMIT::8}
  global:
  - secure: G+WsNhahU/9AUaMCbmG4PhyGaYqzR3gcHJQdXvqo5TLkV+7ScdpOo5PKduH7WskOmMzENc+UD+zjgXx+jH7xOMcXJ2KnId60/TNuH9LibbLE5LmP9eR6H6pAOaf2KxvKvMWcS/Xb7Iu+1w96Egc87EuvK6DwGUC5O2Dmo5gC00Ar+tpkGgGDxhVIl1XHEHLMNWtAlLFdOn7nFISSSU/jFX4PniIQo7G2VnmBnPS1o2BRYLrD07p91JhiJw8fsN79xE+46aFl81iGJVfpoaTpWlAQabDwb62CR9ngDUi6fCncgZ+ZvICVtgmOMjmDxgXw1cas51D6dRYNk9Ljjt+1oyTppcQndJd+RcH7sBwtWQM3M6rLRYSDuKWqfuD4/OZCE7SmI//Wxv6nv6P8tYjEAxo7rfSOKMR3KGCiwwDlXrxIm/NQwoA9OdD6UdRvn1cnSz0G/AVMsdKgixNMiHE+pGvVBpq6uEaQkK0xp4baIj55tuuXznT1YTtq52BWIYOTOK2LSUAMMkwjwvu4JPYfYKH7EYpcUQmqNqJDBdz1uwX/HCEGmGJrYy/X5A/5k5YGjhm38l2LfdaShmPbEXzEG9C0OSvE5FOJ0cu2/gcd5A7PjtbBCOWd0oUH9sThgl5uA+ph8Ugyk5vDRrwJAsezrYdBkzFQPghwPkLQIyYJo1Q=
  - secure: uUH8pcHCUzjfTerDOCdX4qm776Kd9XIQ9in6y4pPn+iwF0TkBzBM1cCXPyz3BYAvCHzTsiDCEjxBCpTt1QhFBIk/PoFFNJ4wi7j4h6A2BnfEWDu9w+mMRUcaB0rSh1E+Q741MCK5WP1eoM7d6KXbHhz0MGt8nnlwywbDU7gya2Pv3xVduKWgG10JmyfxQyTEc32XrKyPtJsK84WrQ2mAj0hnNR6VEElOjlCAXdxAdhPkTeZmK0UzJl5q6ns5MGD2qh8WilLaifZSDLK7mbO//EEl25sdlSe5h/Q5KN08vgjKm/4UezzB4kWsljjTDgp90t9okHnNoHBQiWPanqGV9s1i8ZK8UVS2Yb099tS1hvCMwV2Z0K4wWsyTBWZ0OdNQ3RgAGJfOyZPE5uMqpLwWAZzw82IXN5wd04Lgb2AgLkgQ3+my9GdM0iwXjUrYlSFAZ2x/3TDShyppYPkYo5oERtFJbrmqlUH42m3XTJgOc9WXKyAreErhI8E18cow5F3gnvWTwWYwC+wLRMgamQs/Z3z4Cb5BmipnA+GGcNo7hJ8/7ns2dyktX0ymKoEV1vJ4TwK7VkbNUOH95ygjso6YPtiW7pYyVHaAoZPKA58rtW09u9eFXYeIu2goYojvwWaX6JNL6G6H8kFhVlvcKKby1dZTgxsxfEf3uICuhPDOyO0=

before_install:
- docker logout
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

stages:
- name: Build Docker Image
  if: branch = master

jobs:
  include:
  - stage: Build Docker Image
    script:
    - docker build -t $IMAGE_NAME:latest .
    - docker images
