language: bash
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME="limed/travis-test"
    - COMMIT="${TRAVIS_COMMIT::8}"
    - GO111MODULE=on
    - secure: "uwJdZkbX/BJNhqXd2nt5bKePP4ptoeYMKaSeg0ybV/gr0Ji8ORO97IiSguID1SiE4a1/38fXEbIYeE8ER1OThUG/v55nAcoyrIsR914WOzpha8e+bLtxi1r30HQ9qIDQOuLokUQVXflTCnAPU/0A+s28x9avDuKw3KMRmVscA6HFvDv+cPrnWGux3jFwRxiTNmZIhoR6VWC8lG84zM6RA6uP3rQ78W9sniLhLUc1NdgB10CrSnzivMvlOmvrPZtZFu8mBhZooIEbe/OQLcEVbdh1eTzvHbMXVMVhKh0duzagul/Fy886aFKOYYnTv/vrrFlPBBnhwO9ogKgnQ9Y6GVBbJ9ScSvBrTwWCk01bN7osnliflSjL9EBd0wVdrqFY+91zDuCp3UeZ66yudnF6Gwh7ZI4zjAQelOcKpULZMiWe72gGmIYiqEd7ZJDMZfYePpqZY9c1y3zZKky1mSmWkKY6/zOzGuj2IDwc0913B08Mk4/DIltCzdIgWBzIX7ZUZzkwkY/+Pv+MFFPEn84KzKNhyLnrAEfacyOCD7ND71m7LN6M7/z1/gEOGNZBpJvSBf6+FdMsj+TWoYe6p3CDy1tf4v/w6mQ8p/bVvQIrK2Rks4jkT+p7cE1fLZNQFykNI99EEadKG1Yy5159TUcar3IKV2Rr2IEmC7gXsb+7hn8="
    - secure: "J5OtBwraN0yPeEZKuFKR8zftCFJYFos8UkJV3Yuu1Va5ln7sMdvOC3med7OXHbxaGlFX9QVlJ3Sh3rnzOeqs0zAXADmOYireyBibJGnt71osjfATYrPEdknuj2t07V+MURCWjCUKPU/yH9kwnEe0LsuX3nY/YY51Dk6NI1KZnC7uL9WIiJgP638Y0tqborZCnMZ4B4GilY0SqwbEVMf9t5qdspDKVX+uxDZWD8Nig+Afs4HTDhlDTbqqXV6NN1z7sfMwDmJBf6UXMmo17FN/DMym4qQzM9VVt6JftErpBqRC+rI7ahMP7COvoKJKtOOKxcpbcqnl5IAH1uVsUCax2RJCLIiHCywmf8cExmu+9xdsEkEFYVt52T//MLbmY0Azl7JwGxXK7YzSPkRgx2XZjToceYsaONwdOVOFvwnmxzTP8HGlAf1TBbqxlO8XcKkYspr2eNON5O3ze0oimueiLJMJCCCxeoIc6nwA6Xh9Jw+b8s03T7ERGZFMGip6tZQknzP76Uei7LfyEMNVpH7SjBUxtdW52wAVuSDyyNoi9xDOOmlnuNEbCDhdHo2rNJvvlseprCKEKU7MiVgM8VFJ6d3MdlN1uF5w39n6izKKxQG+QGKyJvwYdCKbCfAcuASW4rUGPVxoJ9YYe0MgL8Zj83eMAB3L2IYF5WIXi5Lj/Zc="

before_sript:
  - SAFE_BRANCH_NAME=$(echo -n $TRAVIS_BRANCH | perl -pe's/[^a-zA-Z0-9_.-]/_/g' )
  - REVISION_TAG="$SAFE_BRANCH_NAME-$COMMIT"
  - if [ "$TRAVIS_TAG" == "" ]; then SYMBOLIC_TAG="$SAFE_BRANCH_NAME-latest"; else SYMBOLIC_TAG="$TRAVIS_TAG"; fi
  - echo "Branch $SAFE_BRANCH_NAME"
  - echo "Tag $TRAVIS_TAG"
  - if [ "$TRAVIS_TAG" == "" ]; then docker pull "$IMAGE_NAME:$SYMBOLIC_TAG" || true; fi


script:
  - docker build --tag "$IMAGE_NAME" --tag "$IMAGE_NAME:$COMMIT" .

before_deploy:
  - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USER" --password-stdin
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$REVISION_TAG"
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$SYMBOLIC_TAG"

deploy:
  provider: script
  on:
    all_branches: true
    condition: $TRAVIS_TAG != "" || $TRAVIS_BRANCH =~ ^(master|prod)$
  script:
    - docker push "$IMAGE_NAME:$REVISION_TAG" && docker push "$IMAGE_NAME:$SYMBOLIC_TAG"
