language: bash
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME="limed/travis-test"
    - COMMIT="${TRAVIS_COMMIT::8}"
    - GO111MODULE=on
    - secure: G+WsNhahU/9AUaMCbmG4PhyGaYqzR3gcHJQdXvqo5TLkV+7ScdpOo5PKduH7WskOmMzENc+UD+zjgXx+jH7xOMcXJ2KnId60/TNuH9LibbLE5LmP9eR6H6pAOaf2KxvKvMWcS/Xb7Iu+1w96Egc87EuvK6DwGUC5O2Dmo5gC00Ar+tpkGgGDxhVIl1XHEHLMNWtAlLFdOn7nFISSSU/jFX4PniIQo7G2VnmBnPS1o2BRYLrD07p91JhiJw8fsN79xE+46aFl81iGJVfpoaTpWlAQabDwb62CR9ngDUi6fCncgZ+ZvICVtgmOMjmDxgXw1cas51D6dRYNk9Ljjt+1oyTppcQndJd+RcH7sBwtWQM3M6rLRYSDuKWqfuD4/OZCE7SmI//Wxv6nv6P8tYjEAxo7rfSOKMR3KGCiwwDlXrxIm/NQwoA9OdD6UdRvn1cnSz0G/AVMsdKgixNMiHE+pGvVBpq6uEaQkK0xp4baIj55tuuXznT1YTtq52BWIYOTOK2LSUAMMkwjwvu4JPYfYKH7EYpcUQmqNqJDBdz1uwX/HCEGmGJrYy/X5A/5k5YGjhm38l2LfdaShmPbEXzEG9C0OSvE5FOJ0cu2/gcd5A7PjtbBCOWd0oUH9sThgl5uA+ph8Ugyk5vDRrwJAsezrYdBkzFQPghwPkLQIyYJo1Q=
    - secure: eqRadwjOhyWYAA2rdg2avNoxnkzB6XQj1Fgbv7EPRFZmQ7kV454j3jsgDQR/etXxsgfY/MOWd9cs1j17XnWHFrKdUGg/nGOYnCXnxFK9gZkaz4WsUBut7ADor9euXpahah99esVHaPeSKL/Ly5ujIAwFfNMieNvK0UV/dOWHuw7PfZ/kCgtInx90yuqMycHxBwTWPWUwEeOZgpxipth6nqlH+HyVM7E7t03SrmcYkE7T/G5/AC096h4yY6Wy+wRPl9K+ZJ/gPkpc5NFRztRfCeUGEbaaZVlmPxPmYS23gf09hZiZvzVARkxBRt83IzVEl2vnv3g4UHsJnD3hWmJIkJRttfVzdmARHVH2FJSjHJ3zMxKEfH9O06jwAbbM4LNCkkn92LnKZEZVlhWvAHnGzDxrUt2VJ07PH5LcMenoT1G6n7LgQKaRmd5tbzQy0IF+WjXjBYWLoks6pQGuot6HnsVtOM2n1n/Wrxx0tGWAsQ7ec/dyll3H0qwCs/C/yWxlPjW90rdfh2dDMAMZOcXB7hAwfCIxM3G61H/JnbACJlHOEppr7uHTXEFmtbS4D3+FaRMR9gwvjs0YEkLwZIzjdj6s//5SWzME60sY1ONdxDsQ7AEMCRqgXEsNrSzKqt0L/6WJUl9pJFYYitY0eGlAZ4Y1pA60OIFhn7HyUkQsHkQ=

before_sript:
  - SAFE_BRANCH_NAME=$(echo -n $TRAVIS_BRANCH | perl -pe's/[^a-zA-Z0-9_.-]/_/g' )
  - REVISION_TAG="$SAFE_BRANCH_NAME-$TRAVIS_COMMIT"
  - if [ "$TRAVIS_TAG" == "" ]; then SYMBOLIC_TAG="$SAFE_BRANCH_NAME-latest"; else SYMBOLIC_TAG="$TRAVIS_TAG"; fi
  - echo "Branch $SAFE_BRANCH_NAME"
  - echo "Tag $TRAVIS_TAG"
  - if [ "$TRAVIS_TAG" == "" ]; then docker pull "$IMAGE_NAME:$SYMBOLIC_TAG" || true; fi


script:
  - docker build --tag "$IMAGE_NAME" --tag "$IMAGE_NAME:$COMMIT" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$REVISION_TAG"
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$SYMBOLIC_TAG"

deploy:
  provider: script
  on:
    all_branches: true
    condition: $TRAVIS_TAG != "" || $TRAVIS_BRANCH =~ ^(master|prod)$
    script:
      - docker push "$IMAGE_NAME:$REVISION_TAG" && docker push "$IMAGE_NAME:$SYMBOLIC_TAG"
