
replicaCount: 1

image:
  repository: limed/travis-test
  pullPolicy: IfNotPresent

hpa:
  enabled: false
  maxReplicas: 10
  # average total CPU usage per pod (1-100)
  cpu:
  # average memory usage per pod (100Mi-1Gi)
  memory:
  # average http requests per second per pod (k8s-prometheus-adapter)
  requests:

serviceAccount:
  create: false
  # Annotations to add to the service account
  annotations: {}
  name:

service:
  enabled: true
  type: ClusterIP
  httpPort: 8081
  externalPort: 8081

resources:
  limits:
  requests:
    cpu: 1m
    memory: 16Mi
