apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "travis-test.fullname" . }}
  labels:
    {{- include "travis-test.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "travis-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "travis-test.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "travis-test.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort | default "8081"  }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
