apiVersion: v1
kind: Service
metadata:
  name: {{ include "travis-test.fullname" . }}
  labels:
    {{- include "travis-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort | default "8081" }}
  selector:
    {{- include "travis-test.selectorLabels" . | nindent 4 }}
