apiVersion: v1
kind: Service
metadata:
  name: {{ include "travis-test.fullname" . }}
  labels:
    {{- include "travis-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.httpPort | default 8081 }}
      protocol: TCP
      name: http
  selector:
    {{- include "travis-test.selectorLabels" . | nindent 4 }}
